- name: Create VNC user
  user:
    name: "{{ vnc_user }}"
    shell: /bin/bash
    create_home: yes
    home: "/home/{{ vnc_user }}"
    state: present

- name: Create .vnc directory for VNC user
  file:
    path: "/home/{{ vnc_user }}/.vnc"
    state: directory
    owner: "{{ vnc_user }}"
    group: "{{ vnc_user }}"
    mode: '0700'

- name: Create VNC password file
  shell: echo '{{ vnc_password }}' | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd
  args:
    creates: "/home/{{ vnc_user }}/.vnc/passwd"
  become_user: "{{ vnc_user }}"

- name: Create .vnc/xstartup to XFCE
  copy:
    dest: "/home/{{ vnc_user }}/.vnc/xstartup"
    content: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec startxfce4
    owner: "{{ vnc_user }}"
    group: "{{ vnc_user }}"
    mode: '0755'

- name: Set permissions for VNC password file
  file:
    path: "/home/{{ vnc_user }}/.vnc/passwd"
    owner: "{{ vnc_user }}"
    group: "{{ vnc_user }}"
    mode: '0600'

- name: Launch VNC server for user
  command: /usr/bin/vncserver :1
  become_user: "{{ vnc_user }}"
  args:
    creates: "/home/{{ vnc_user }}/.vnc/$(hostname):1.pid"
  when: start_vnc_server
